import React from "react";
import Header from '../Navbar/Navbar';
const Terms = () => {

    return (
        <div style={{ backgroundColor: '#000' }}>
            <Header />
            <div style={{ color: 'white', margin: '0 auto', width: '70%' }} >

                <h1>Offside Privacy Policy</h1>
                <p>
                    This Privacy Policy forms part of our <b>Terms of Service</b>, which describes the terms under which you use our
                    Services. This Privacy Policy should therefore be read in conjunction with those terms.
                </p>
                <p>
                    This Privacy Policy sets out how we, <b>Kalekik Inc.</b> (“Offside”), use and protect your personal data that
                    you
                    provide to us, or that is otherwise obtained or generated by us, in connection with your use of our live match
                    discussion <b>services</b> (the “Services”). For the purposes of this Privacy Policy, ‘we’, ‘us’ and ‘our’
                    refers to
                    Offside, and ‘you’ refers to you, the user of the Services.
                </p>
                <p>
                    Offside respects the privacy of its Users and is committed to protect it in all respects. With a view to offer
                    an enriching and holistic internet experience to its Users, Offside offers a vast repository of Services. The
                    information about the User is collected by Offside as (i) information supplied by Users and (ii) information
                    automatically tracked during User's navigation on Offside.
                </p>
                <p>
                    Before you submit any information to the application, please read this Privacy Policy for an explanation of how
                    we will treat your personal information. By using any part of the application, you consent to the collection,
                    use, disclosure and transfer of your personal information for the purposes outlined in this Privacy Policy and
                    to the collection, processing and maintenance of this information. If you do not agree to this Privacy Policy,
                    please do not use the application. Your use of any part of the application indicates your acceptance of this
                    Privacy Policy and of the collection, use and disclosure of your personal information in accordance with this
                    Privacy Policy. While you have the option not to provide us with certain information, withdraw your consent to
                    collect certain information, request temporary suspension of collection of information or request deletion of
                    information collected, kindly note that in such an event you may not be able to take full advantage of the
                    entire scope of features and services offered to you and we reserve the right not to provide you with our
                    services.
                </p>

                <h4>Purpose and Usage:</h4>
                <p>
                    To avail certain Services on the application, Users would be required to provide certain information for the
                    registration process namely:
                </p>
                <ol>
                    <li>Username</li>
                    <li>Email address</li>
                    <li>Date of birth</li>
                    <li>Phone number</li>
                    <li>Contacts list</li>
                    <li>Full name</li>
                    <li>Gender</li>
                </ol>
                <p>
                    In the course of providing you with access to the Services , and in order to provide you access to the
                    features
                    offered through the application and to verify your identity, secure your account details, you may give us
                    the
                    permission to capture, record your device information, operating system information, network information,
                    location information. You may also be required to furnish additional information, including your Permanent
                    Account Number.
                </p>
                <p>
                    In certain instances, we may also collect Sensitive Personal Information (“SPI”) from you on the
                    application.
                    SPI means such personal information which consists of information relating to your physical, physiological
                    and
                    mental health condition; medical records and history; biometric information, sexual orientation and
                    financial
                    information.
                </p>
                <p>
                    In the course of providing the Services , Users may invite other existing Users or other users ("Invited
                    Users")
                    to participate in any of the Services by providing the mobile number of such users. Offside may thereafter
                    use
                    this information to contact the Invited User and invite such user to register with Offside (if such Invited
                    User
                    is not an existing User) and use the application in relation to which such person was invited by the User.
                    The
                    participation of the Invited User in any part of the application shall be subject to the terms of this
                    Privacy
                    Policy and the Terms and Conditions for the use of the application. The User hereby represents that the
                    Invited
                    Users have consented and agreed to such disclosure to and use of their mobile number by Offside.
                </p>
                <p>
                    All required information is specific and based on the kind Services the User wishes to participate in or
                    access,
                    and will be utilized for the purpose of providing services, including but not limited to the Services
                    requested
                    by the User. The information as supplied by the Users enables us to improve the Services and provide you the
                    most user-friendly game experience
                </p>
                <p>
                    Offside may also share such information with affiliates and third parties in limited circumstances,
                    including
                    for the purpose of providing services requested by the User, complying with legal process, preventing fraud
                    or
                    imminent harm, and ensuring the security of our network and services.
                </p>

                <h4>Phone Number and Contacts list</h4>
                <p>
                    Offside uses phone numbers as unique identifiers so that it is easy for you to switch from SMS and other
                    messaging apps and retain your social graph. We ask your permission before syncing your contacts.
                </p>
                <p>
                    We are NOT storing the contact list of any user in our internal database. We just ask for access to the
                    phonebook ephemerally and our API just checks which contacts of the users are on our app to retrieve the
                    friend
                    list, we don't store that data in our internal Database.
                </p>
                <p>
                    We upload & store your up-to-date contacts list in order to notify you as soon as one of your contacts
                    signs up
                    for Offside and to properly display names in notifications. We only need the number and name as saved by
                    you for
                    this to work and store no other data about your contacts.
                </p>

                <h4>Disclosure/Sharing:</h4>
                <p>
                    Offside may also share information as provided by you and data concerning usage of the platform with
                    third party
                    service providers engaged by Offside, for the purpose of data analytics or other similar purposes,
                    for the
                    purpose of storage, improving the services and helping Offside serve you better.
                </p>
                <p>
                    Where we propose to use your personal information (that is, information that may be used to identify
                    the User
                    and that is not otherwise publicly available) for any other uses we will ensure that we notify you
                    first. You
                    will also be given the opportunity to withhold or withdraw your consent for your use other than as
                    listed above.
                </p>
                <p>
                    By using the application, you hereby expressly agree and grant consent to the collection, use and
                    storage of
                    this information by Offside. Offside reserves the right to share, disclose and transfer information
                    collected
                    hereunder with its own affiliates. In the event Offside sells or transfers all or a portion of its
                    business
                    assets, consumer information may be one of the business assets that are shared, disclosed or
                    transferred as part
                    of the transaction. You hereby expressly grant consent and permission to Offside for disclosure and
                    transfer of
                    information to such third parties. Offside may share information as provided by you and data
                    concerning usage of
                    the platform with its commercial partners for the purpose of facilitating user engagement, for
                    marketing and
                    promotional purposes and other related purposes. Further, Offside reserves the right to disclose
                    personal
                    information as obligated by law, in response to duly authorized legal process, governmental requests
                    and as
                    necessary to protect the rights and interests of Offside.
                </p>

                <h4>Use of Cookies:</h4>
                <p>
                    To improve the effectiveness and usability of the application for our Users, we use "cookies",
                    or such similar
                    electronic tools to collect information to assign each visitor a unique random number as a User
                    Identification
                    (User ID) to understand the User's individual interests using the identified computer. Unless
                    the User
                    voluntarily identifies himself/herself (e.g., through registration), Offside has no way of
                    knowing who the User
                    is, even if we assign a cookie to the User's computer. The only personal information a cookie
                    can contain is
                    information supplied by the User. A cookie cannot read data off the User's hard drive. Offside’s
                    advertisers may
                    also assign their own cookies to the User's browser (if the User clicks on their ad banners), a
                    process that
                    Offside does not control.
                </p>
                <p>
                    Offside's web servers automatically collect limited information about User's computer's
                    connection to the
                    Internet, including User's IP address, when the User visits the application. (User's IP address
                    is a number that
                    lets computers attached to the Internet know where to send data to the User -- such as the web
                    pages viewed by
                    the User). The User's IP address does not identify the User personally. Offside uses this
                    information to deliver
                    its web pages to Users upon request, to tailor its application to the interests of its users, to
                    measure traffic
                    within the application and let advertisers know the geographic locations from where Offside's
                    visitors come.
                </p>

                <h4>Advanced features</h4>
                <p>
                    We may use some aggregated data about how you use Offside to build useful features. For example,
                    when you open
                    the application, Offside displays your friends ratings at the top of the screen. To decide the
                    order, we
                    calculate a rating that helps us decide the order of friends you interact with mostly.
                </p>

                <h4>Our Services</h4>
                <p>
                    Offside is a cloud service. We will process your data to deliver your cloud chat history,
                    including messages, media and files, to any devices of your choosing without a need for you to
                    use third-party backups or cloud storage. Offside is a cloud service. We store messages, photos,
                    videos and documents from your cloud chats on our servers so that you can access your data from
                    any of your devices anytime without having to rely on third-party backups. All data is stored
                    heavily encrypted and the encryption keys in each case are stored in several other data centers
                    in different jurisdictions. This way local engineers or physical intruders cannot get access to
                    user data.
                </p>

                <h4>Links:</h4>
                <p>
                    Offside also includes links to other applications. Such applications are governed by their respective privacy
                    policies, which are beyond Offside's control. Once the User leaves Offside's servers (the User can tell where
                    he/she is by checking the URL in the location bar on the User's browser), use of any information provided by the
                    User is governed by the privacy policy of the operator of the site which the User is visiting. That policy may
                    differ from Offside's own. If the User can't find the privacy policy of any of these sites via a link from the
                    site's homepage, the User may contact the site directly for more information. Offside is not responsible for the
                    privacy practices or the content of such applications.
                </p>

                <h4>Security Procedures:</h4>
                <p>
                    All information gathered on Offside is securely stored within the Offside controlled database. The database is
                    stored on servers secured behind a firewall; access to such servers being password-protected and strictly
                    limited based on need-to-know basis. However, we understand that as effective as our security measures are, no
                    security system is impenetrable. Thus, we cannot guarantee the security of our database, nor can we guarantee
                    that information you supply will not be intercepted while being transmitted to us over the Internet. Further,
                    any information you include in a posting to the discussion areas will be available to anyone with Internet
                    access. By using the application, you understand and agree that your information may be used in or transferred
                    to countries other than India.
                </p>
                <p>
                    Offside also believes that the internet is an ever-evolving medium. We may periodically review from time to time
                    and change our privacy policy to incorporate such future changes as may be considered appropriate, without any
                    notice to you. Our use of any information we gather will always be consistent with the policy under which the
                    information was collected, regardless of what the new policy may be. Any changes to our privacy policy will be
                    posted on this page, so you are always aware of what information we collect, how we use it, how we store it and
                    under what circumstances we disclose it.
                </p>

                <h4>Advertising:</h4>
                <p>
                    When Offside presents information to its online advertisers -- to help them understand our audience and confirm
                    the value of advertising on the application -- it is usually in the form of aggregated statistics on traffic to
                    various pages within our site. When you register with Offside, we contact you from time to time about updating
                    your content to provide features which we believe may benefit you.
                </p>
                <p>
                    Several deceptive emails, applications, blogs etc. claiming to be from or associated with Offside may or are
                    circulating on the Internet. These emails, applications, blogs etc. often include our logo, photos, links,
                    content or other information. Some emails, applications, blogs etc. call the user requesting the user to provide
                    login name, password etc. or inform the user that the user has won a prize/ gift or provide a method to commit
                    an illegal/ unauthorized act or deed or request detailed personal information or a payment of some kind. The
                    sources and contents of these emails, applications, blogs etc. and accompanying materials are in no way
                    associated with Offside. For your own protection, we strongly recommend not responding to such emails or using
                    these applications, blogs etc. We may use the information provided by you to Offside, including your email
                    address or phone number, to contact you about the Services availed by you or to inform you of our updated
                    Services if any.
                </p>

                <h4>Conditions of Use:</h4>
                <p>
                    Offside DOES NOT WARRANT THAT THIS application, IT’S SERVERS, OR EMAIL SENT BY US OR ON OUR BEHALF ARE VIRUS
                    FREE. Offside WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS application,
                    INCLUDING, BUT NOT LIMITED TO COMPENSATORY, DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL AND CONSEQUENTIAL
                    DAMAGES, LOSS OF DATA, GOODWILL, BUSINESS OPPORTUNITY, INCOME OR PROFIT, LOSS OF OR DAMAGE TO PROPERTY AND
                    CLAIMS OF THIRD PARTIES. IN NO EVENT WILL Offside BE LIABLE FOR ANY DAMAGES WHATSOEVER IN AN AMOUNT IN EXCESS OF
                    AN AMOUNT OF INR 100.
                </p>

                <h4>Offside’s License To You:</h4>
                <p>
                    We grant you a limited, revocable, non-exclusive, non-sublicensable, and non-transferable license to use our
                    Services, subject to and in accordance with our Terms. This license is for the sole purpose of enabling you to
                    use our Services in the manner permitted by our Terms. No licenses or rights are granted to you by implication
                    or otherwise, except for the licenses and rights expressly granted to you.
                </p>

                <h4>Retention of Data:</h4>
                <p>
                    Your personal information may be retained and may continue to be used until: (i) the relevant purposes for the
                    use of your information described in this Privacy Policy are no longer applicable; and (ii) we are no longer
                    required by applicable law, regulations, contractual obligations or legitimate business purposes to retain your
                    personal information and the retention of your personal information is not required for the establishment,
                    exercise or defense of any legal claim.
                </p>

                <h4>User Account and Data Deletion:</h4>
                <p>
                    Users are entitled to request Offside to delete their User accounts and their personal information by sending an
                    email with their written request to <b>help@offside.club</b>
                </p>
                <p>
                    We will do our best to respond promptly and in any event within one month of the following:
                </p>
                <ul>
                    <li>
                        Our receipt of your written request; or
                    </li>
                    <li>
                        Our receipt of any further information we may ask you to provide to enable us to comply with your request,
                        whichever is later.
                    </li>
                </ul>
                <p>
                    As an alternative to account deletion, by writing to <b>help@offside.club</b>, you also have the option to
                    request
                    either:
                </p>
                <ul>
                    <li>
                        (i) the suspension of your account, after which you will not be able to participate in Game hub or chat with
                        others but will be able to sue other parts of the application; or
                    </li>
                    <li>
                        (ii) temporary deactivation of your account, where you will no longer be able to log into the application
                        but which allows you to request reactivation of your account with all your account data.
                    </li>
                </ul>
                <p>
                    If you proceed with permanent deactivation of your account, you will lose access to the application and the
                    Services, including any User data and personal information associated with your account. Users may request for
                    account restoration within six (6) months from the date of notification of account deletion by Offside by
                    writing to <b>help@offside.club</b>
                </p>
                <p>
                    When you request deletion of your data, we follow a deletion process that ensures that your data is safely and
                    completely removed from our servers or retained only in anonymised form. We try to ensure that our services
                    protect information from accidental or malicious deletion. Because of this, there may be delays between when you
                    request deletion and when copies are deleted from our active and backup systems.
                </p>

                <h4>Applicable Law and Jurisdiction:</h4>
                <p>
                    By visiting this application, you agree that the laws of the Republic of India without regard to its conflict of
                    laws principles, govern this Privacy Policy and any dispute arising in respect hereof shall be subject to and
                    governed by the dispute resolution process set out in the Terms and Conditions.
                </p>

                <h4>Updating Information:</h4>
                <p>
                    You will promptly notify Offside if there are any changes, updates or modifications to your information.
                    Further, you may also review, update or modify your information and user preferences by logging into your
                    Profile page on the application.
                </p>

                <h4>Contact Us:</h4>
                <p>
                    Any questions or clarifications with respect to this Policy or any complaints, comments, concerns or feedback
                    can be sent to Offside at: <b>help@offside.club</b>
                </p>

                <h4>--------------------------------------------------------------------------------------------------------------------------------------------
                </h4>

                <h1>Terms & Service</h1>

                <ol>
                    <li>
                        Offside
                        <p>
                            Offside is the flagship brand of Kalekik Inc. ("Offside"). Through Offside, and the Offside App, Offside
                            operates a portal through which it offers group/personal chatting service, live cricket scores,
                            prediction contests, rewards based on referral and predictions, and match specific Game hub combining
                            chat service, live match updates and predictions. Offside as used herein shall be construed as a
                            collective reference to Offside and the Offside App. The user must be <b>16 years or above</b> to use
                            Offside.
                        </p>
                    </li>
                </ol>
                <ol>
                    <li>
                        Usage of Offside
                        <ul>
                            <li>
                                Any person ("<b>User</b>") accessing Offside or the Offside App ('Offside platform') for
                                interacting with others & participating in predictions, available on Offside platform shall
                                be bound by these Terms and Conditions, and all other rules, regulations and terms of use
                                referred to herein or provided by Offside in relation to any Offside Services.
                            </li>
                            <li>
                                You must access and use our Services only for legal, authorized, and acceptable purposes. You will
                                not use (or assist others in using) our Services in ways that: (a) violate, misappropriate, or
                                infringe the rights of Offside, our users, or others, including privacy, publicity, intellectual
                                property, or other proprietary rights; (b) are illegal, obscene, defamatory, threatening,
                                intimidating, harassing, hateful, racially or ethnically offensive, or instigate or encourage
                                conduct that would be illegal or otherwise inappropriate, such as promoting violent crimes,
                                endangering or exploiting children or others, or coordinating harm; (c) involve publishing
                                falsehoods, misrepresentations, or misleading statements; (d) impersonate someone; (e) involve
                                sending illegal or impermissible communications such as bulk messaging, auto-messaging,
                                auto-dialing, and the like; or (f) involve any non-personal use of our Services unless otherwise
                                authorized by us.
                            </li>
                            <li>
                                Offside shall be entitled to modify these Terms and Conditions, rules, regulations and terms of use
                                referred to herein or provided by Offside in relation to any Offside Services, at any time, by
                                posting the same on Offside. Use of Offside constitutes the User's acceptance of such Terms and
                                Conditions, rules, regulations and terms of use referred to herein or provided by Offside in
                                relation to any Offside Services, as may be amended from time to time. Offside may, at its sole
                                discretion, also notify the User of any change or modification in these Terms and Conditions, rules,
                                regulations and terms of use referred to herein or provided by Offside, by way of sending an email
                                to the User's registered email address or posting notifications in the User accounts. The User may
                                then exercise the options provided in such an email or notification to indicate non-acceptance of
                                the modified Terms and Conditions, rules, regulations and terms of use referred to herein or
                                provided by Offside. If such options are not exercised by the User within the time frame prescribed
                                in the email or notification, the User will be deemed to have accepted the modified Terms and
                                Conditions, rules, regulations and terms of use referred to herein or provided by Offside
                            </li>
                            <li>
                                Certain Offside Services being provided on Offside may be subject to additional rules and
                                regulations set down in that respect. To the extent that these Terms and Conditions are inconsistent
                                with the additional conditions set down, the additional conditions shall prevail
                            </li>
                            <li>
                                Offside may, at its sole and absolute discretion:
                            </li>
                            <ol type="a">
                                <li>
                                    Restrict, suspend, or terminate any User's access to all or any part of Offside or Offside
                                    Platform Services;
                                </li>
                                <li>
                                    Change, suspend, or discontinue all or any part of the Offside Platform Services;
                                </li>
                                <li>
                                    Reject, move, or remove any material that may be submitted by a User;
                                </li>
                                <li>
                                    Move or remove any content that is available on Offside Platform;
                                </li>
                                <li>
                                    Deactivate or delete a User's account and all related information and files on the account;
                                </li>
                                <li>
                                    Establish general practices and limits concerning use of Offside Platform;
                                </li>
                                <li>
                                    Assign its rights and liabilities to all User accounts hereunder to any entity (post such
                                    assignment intimation of such assignment shall be sent to all Users to their registered email
                                    ids)
                                </li>
                            </ol>

                            <li>
                                In the event any User breaches, or Offside reasonably believes that such User has breached these
                                Terms and Conditions, or has illegally or improperly used Offside or the Offside Services,
                                Offside may, at its sole and absolute discretion, and without any notice to the User, restrict,
                                suspend or terminate such User's access to all or any part of Offside Contests or the Offside
                                Platform, deactivate or delete the User's account and all related information on the account,
                                delete any content posted by the User on Offside and further, take technical and legal steps as
                                it deems necessary
                            </li>
                            <li>
                                If Offside charges its Users a platform fee in respect of any Offside Services, Offside shall,
                                without delay, repay such platform fee in the event of suspension or removal of the User's
                                account or Offside Services on account of any negligence or deficiency on the part of Offside,
                                but not if such suspension or removal is affected due to:
                                <ol type="a">
                                    <li>
                                        any breach or inadequate performance by the User of any of these Terms and Conditions; or
                                    </li>
                                    <li>
                                        any circumstances beyond the reasonable control of Offside.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                Users consent to receiving communications such as announcements, administrative messages and
                                advertisements from Offside or any of its partners, licensors or associates.
                            </li>
                        </ul>
                    </li>
                    <li>
                        Intellectual Property
                        <ul>
                            <li>
                                Offside includes a combination of content created by Offside, its partners, affiliates, licensors,
                                associates and/or Users. The intellectual property rights ("<b>Intellectual Property Rights</b>") in
                                all
                                software underlying Offside and the Offside Platform and material published on Offside, including
                                (but not limited to) games, predictions, Contests, software, advertisements, written content,
                                photographs, graphics, images, illustrations, marks, logos, audio or video clippings and Flash
                                animation, is owned by Offside, its partners, licensors and/or associates. Users may not modify,
                                publish, transmit, participate in the transfer or sale of, reproduce, create derivative works of,
                                distribute, publicly perform, publicly display, or in any way exploit any of the materials or
                                content on Offside either in whole or in part without express written license from Offside
                            </li>
                            <li>
                                Users may request permission to use any Offside content by writing in to <b>help@offside.club</b>.
                            </li>
                            <li>
                                Users are solely responsible for all materials (whether publicly posted or privately transmitted)
                                that they upload, post, e-mail, transmit, or otherwise make available on Offside ("<b>Users'
                                    Content</b>").
                                Each User represents and warrants that he/she owns all Intellectual Property Rights in the User's
                                Content and that no part of the User's Content infringes any third party rights. Users further
                                confirm and undertake to not display or use of the names, logos, marks, labels, trademarks,
                                copyrights or intellectual and proprietary rights of any third party on Offside. Users agree to
                                indemnify and hold harmless Offside, its directors, employees, affiliates and assigns against all
                                costs, damages, loss and harm including towards litigation costs and counsel fees, in respect of any
                                third party claims that may be initiated including for infringement of Intellectual Property Rights
                                arising out of such display or use of the names, logos, marks, labels, trademarks, copyrights or
                                intellectual and proprietary rights on Offside, by such User or through the User's commissions or
                                omissions
                            </li>
                            <li>
                                Users hereby grant to Offside and its affiliates, partners, licensors and associates a worldwide,
                                irrevocable, royalty-free, non-exclusive, sub-licensable license to use, reproduce, create
                                derivative works of, distribute, publicly perform, publicly display, transfer, transmit, and/or
                                publish Users' Content for any of the following purposes:
                            </li>
                            <ol type="a">
                                <li>
                                    displaying Users' Content on Offside
                                </li>
                                <li>
                                    distributing Users' Content, either electronically or via other media, to other Users seeking to
                                    download or otherwise acquire it, and/or
                                </li>
                                <li>
                                    storing Users' Content in a remote database accessible by end users, for a charge.
                                </li>
                                <li>
                                    This license shall apply to the distribution and the storage of Users' Content in any form,
                                    medium, or technology.
                                </li>
                            </ol>
                            <li>
                                All names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on
                                Offside(s) belonging to any person (including User), entity or third party are recognized as
                                proprietary to the respective owners and any claims, controversy or issues against these names,
                                logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights must be directly
                                addressed to the respective parties under notice to Offside.
                            </li>
                        </ul>
                    </li>
                    <li>
                        Third Party Sites, Services and Products
                        <ul>
                            <li>
                                Offside may contain links to other Internet sites owned and operated by third parties. Users' use of
                                each of those sites is subject to the conditions, if any, posted by the sites. Offside does not
                                exercise control over any Internet sites apart from Offside and cannot be held responsible for any
                                content residing in any third-party Internet site. Offside's inclusion of third-party content or
                                links to third-party Internet sites is not an endorsement by Offside of such third-party Internet
                                site.
                            </li>
                            <li>
                                Users' correspondence, transactions/offers or related activities with third parties, including
                                payment providers and verification service providers, are solely between the User and that third
                                party. Users' correspondence, transactions and usage of the services/offers of such third party
                                shall be subject to the terms and conditions, policies and other service terms adopted/implemented
                                by such third party, and the User shall be solely responsible for reviewing the same prior to
                                transacting or availing of the services/offers of such third party. User agrees that Offside will
                                not be responsible or liable for any loss or damage of any sort incurred as a result of any such
                                transactions/offers with third parties. Any questions, complaints, or claims related to any third
                                party product or service should be directed to the appropriate vendor.
                            </li>
                            <li>
                                Offside contains content that is created by Offside as well as content provided by third parties.
                                Offside does not guarantee the accuracy, integrity, quality of the content provided by third parties
                                and such content may not be relied upon by the Users in utilizing the Offside Services provided on
                                Offside including while participating in any of the contests hosted on Offside.
                            </li>
                        </ul>
                    </li>
                    <li>
                        Privacy Policy
                        <p>
                            All information collected from Users, such as registration and credit card information, is subject to
                            Offside's Privacy Policy which is available at Privacy Policy.
                        </p>
                    </li>
                    <li>
                        User Conduct
                        <ul>
                            <li>
                                Users agree to abide by these Terms and Conditions and all other rules, regulations and terms of use
                                of the application. In the event User does not abide by these Terms and Conditions and all other
                                rules, regulations and terms of use, Offside may, at its sole and absolute discretion, take
                                necessary remedial action, including but not limited to:
                            </li>
                            <ol type="a">
                                <li>
                                    restricting, suspending, or terminating any User's access to all or any part of Offside
                                    Services;
                                </li>
                                <li>
                                    deactivating or deleting a User's account and all related information and files on the account;;
                                    or
                                </li>
                                <li>
                                    refraining from awarding any prize(s) to such User.
                                </li>
                            </ol>
                            <li>
                                Users agree to provide true, accurate, current and complete information at the time of registration
                                and at all other times (as required by Offside). Users further agree to update and keep updated
                                their registration information
                            </li>
                            <li>
                                A User shall not register or operate more than one User account with Offside.
                            </li>
                            <li>
                                Users agree to ensure that they can receive all communication from Offside by marking e-mail or
                                sending SMSs from Offside as part of their "safe senders'' list. Offside shall not be held liable if
                                any e-mail/SMS remains unread by a User as a result of such e-mail getting delivered to the User's
                                junk or spam folder.
                            </li>
                            <li>
                                Any password issued by Offside to a User may not be revealed to anyone else. Users may not use
                                anyone else's password. Users are responsible for maintaining the confidentiality of their accounts
                                and passwords. Users agree to immediately notify Offside of any unauthorized use of their passwords
                                or accounts or any other breach of security.
                            </li>
                            <li>
                                Users agree to exit/log-out of their accounts at the end of each session. Offside shall not be
                                responsible for any loss or damage that may result if the User fails to comply with these
                                requirements.
                            </li>
                            <li>
                                Users agree not to use cheats, exploits, automation, software, bots, hacks or any unauthorized third
                                party software designed to modify or interfere with Offside Services and/or Offside experience or
                                assist in such activity.
                            </li>
                            <li>
                                Users agree not to copy, modify, rent, lease, loan, sell, assign, distribute, reverse engineer,
                                grant a security interest in, or otherwise transfer any right to the technology or software
                                underlying Offside or Offside’s Services.
                            </li>
                            <li>
                                Users agree that without Offside's express written consent, they shall not modify or cause to be
                                modified any files or software that are part of Offside's Services.
                            </li>
                            <li>
                                Users agree not to disrupt, overburden, or aid or assist in the disruption or overburdening of (a)
                                any computer or server used to offer or support Offside or the Offside’s Services (each a "Server");
                                or (2) the enjoyment of Offside Services by any other User or person.
                            </li>
                            <li>
                                Users agree not to institute, assist or become involved in any type of attack, including without
                                limitation to distribution of a virus, denial of service, or other attempts to disrupt Offside
                                Services or any other person's use or enjoyment of Offside Services.
                            </li>
                            <li>
                                Users shall not attempt to gain unauthorized access to the User accounts, Servers or networks
                                connected to Offside Services by any means other than the User interface provided by Offside,
                                including but not limited to, by circumventing or modifying, attempting to circumvent or modify, or
                                encouraging or assisting any other person to circumvent or modify, any security, technology, device,
                                or software that underlies or is part of Offside Services.
                            </li>
                            <li>
                                Users shall not publish any content that is patently false and untrue, and is written or published
                                in any form, with the intent to mislead or harass a person, entity or agency for financial gain or
                                to cause any injury to any person.
                            </li>
                            <li>
                                Without limiting the foregoing, Users agree not to use Offside for any of the following:
                            </li>
                            <ol type="a">
                                <li>
                                    To engage in any obscene, offensive, indecent, racial, communal, anti-national, objectionable,
                                    defamatory or abusive action or communication;
                                </li>
                                <li>
                                    To harass, stalk, threaten, or otherwise violate any legal rights of other individuals;
                                </li>
                                <li>
                                    To publish, post, upload, e-mail, distribute, or disseminate (collectively, "Transmit") any
                                    inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful content;
                                </li>
                                <li>
                                    To Transmit files that contain viruses, corrupted files, or any other similar software or
                                    programs that may damage or adversely affect the operation of another person's computer,
                                    Offside, any software, hardware, or telecommunications equipment;
                                </li>
                                <li>
                                    To advertise, offer or sell any goods or services for any commercial purpose on Offside without
                                    the express written consent of Offside;
                                </li>
                                <li>
                                    To download any file, recompile or disassemble or otherwise affect our products that you know or
                                    reasonably should know cannot be legally obtained in such manner;
                                </li>
                                <li>
                                    To falsify or delete any author attributions, legal or other proper notices or proprietary
                                    designations or labels of the origin or the source of software or other material;
                                </li>
                                <li>
                                    To restrict or inhibit any other user from using and enjoying any public area within our sites;
                                </li>
                                <li>
                                    To collect or store personal information about other Users;
                                </li>
                                <li>
                                    To interfere with or disrupt Offside, servers, or networks;
                                </li>
                                <li>
                                    To impersonate any person or entity, including, but not limited to, a representative of Offside,
                                    or falsely state or otherwise misrepresent User's affiliation with a person or entity;
                                </li>
                                <li>
                                    To forge headers or manipulate identifiers or other data in order to disguise the origin of any
                                    content transmitted through Offside or to manipulate User's presence on Offside(s);
                                </li>
                                <li>
                                    To take any action that imposes an unreasonably or disproportionately large load on our
                                    infrastructure;
                                </li>
                                <li>
                                    To engage in any illegal activities. You agree to use our bulletin board services, chat areas,
                                    news groups, forums, communities and/or message or communication facilities (collectively, the
                                    "Forums") only to send and receive messages and material that are proper and related to that
                                    particular Forum.
                                </li>
                                <li>
                                    To engage in any action that threatens the unity, integrity, defense, security or sovereignty of
                                    India, friendly relations with foreign States, or public order, or causes incitement to the
                                    commission of any cognisable offense or prevents investigation of any offense or is insulting
                                    other nations.
                                </li>
                            </ol>
                            <li>
                                If a User chooses a username that, in Offside's considered opinion is obscene, indecent, abusive or
                                that might subject Offside to public disparagement or scorn, or a name which is an official
                                team/league/franchise names and/or name of any sporting personality, as the case may be, Offside
                                reserves the right, without prior notice to the User, to restrict usage of such names, which in
                                Offside’s opinion fall within any of the said categories and/or change such username and intimate
                                the User or delete such username and posts from Offside, deny such User access to Offside, or any
                                combination of these options.
                            </li>
                            <li>
                                Unauthorized access to Offside is a breach of these Terms and Conditions, and a violation of the
                                law. Users agree not to access Offside by any means other than through the interface that is
                                provided by Offside for use in accessing Offside. Users agree not to use any automated means,
                                including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any
                                part of our sites, except those automated means that we have approved in advance and in writing.
                            </li>
                            <li>
                                Use of Offside is subject to existing laws and legal processes. Nothing contained in these Terms and
                                Conditions shall limit Offside's right to comply with governmental, court, and law-enforcement
                                requests or requirements relating to Users' use of Offside.
                            </li>
                            <li>
                                Users may reach out to Offside through -
                            </li>
                            <ol type="a">
                                <li>
                                    help@offside.club if the user has any concerns with regard to a match and/or predictions within
                                    Forty Eight (48) hours of winner declaration for the concerned predictions.
                                </li>
                            </ol>
                            <li>
                                Persons below the age of sixteen (16) years are not allowed to participate in any of the prediction
                                games (by whatever name called) on the Offside Platform. The Users will have to disclose their real
                                age at the time of getting access into the Offside Platform.
                            </li>
                            <li>
                                Offside may not be held responsible for any content contributed by Users on the Offside.
                            </li>
                        </ul>
                    </li>
                    <li>
                        Conditions of Participation:
                        <p>
                            By entering a Contest, the user agrees to be bound by these Terms and the decisions of Offside. Subject
                            to the terms and conditions stipulated herein below, the Company, at its sole discretion, may disqualify
                            any user from a Contest, refuse to award benefits or prizes and require the return of any prizes, if the
                            user engages in unfair conduct, which the Company deems to be improper, unfair or otherwise adverse to
                            the operation of the Contest or is in any way detrimental to other Users which includes, but is not
                            limited to:
                        </p>
                        <ul>
                            <li>
                                Falsifying one's' own personal information (including, but not limited to, name, email address, bank
                                account details and/or any other information or documentation as may be requested by Offside to
                                enter a contest and/or claim a prize/winning.;
                            </li>
                            <li>
                                Engaging in any type of financial fraud or misrepresentation including unauthorized use of
                                credit/debit instruments, payment wallet accounts etc. to enter a Contest or claim a prize. It is
                                expressly clarified that the onus to prove otherwise shall solely lie on the user.;
                            </li>
                            <li>
                                Colluding with any other user(s) or engaging in any type of syndicate play;
                            </li>
                            <li>
                                Any violation of prediction contest rules or the Terms of Use;
                            </li>
                            <li>
                                Accumulating points or prizes through unauthorized methods such as automated bots, or other
                                automated means;
                            </li>
                            <li>
                                Using automated means (including but not limited to harvesting bots, robots, parser, spiders or
                                screen scrapers) to obtain, collect or access any information on the application or of any User for
                                any purpose
                            </li>
                            <li>
                                Any type of misuse of the Invite Friends program, or misuse of any other offers or promotions;
                            </li>
                            <li>
                                Tampering with the administration of a Prediction contest or trying to in any way tamper with the
                                computer programs or any security measure associated with a Contest;
                            </li>
                            <li>
                                Obtaining other users’ information without their express consent and/or knowledge and/or spamming
                                other users (Spamming may include but shall not be limited to send unsolicited emails to users,
                                sending bulk emails to Offside Users, sending unwarranted email content either to selected Users or
                                in bulk); or
                            </li>
                            <li>
                                Abusing the application in any way (‘unparliamentary language, slangs or disrespectful words’ are
                                some of the examples of Abuse)
                            </li>
                        </ul>
                        <p>
                            It is clarified that in case a User is found to be in violation of this policy, Offside reserves its
                            right to initiate appropriate Civil/Criminal remedies as it may be advised other than forfeiture and/or
                            recovery of prize money if any.
                        </p>
                    </li>
                    <li>
                        Tabulation of prediction points
                        <p>
                            Offside may obtain the score feed and other information required for the computation and tabulation of
                            prediction points from third party service provider(s) and/or official application of the match
                            organizer. In the rare event that any error in the computation or tabulation of prediction points,
                            selection of winners, abandonment of a match etc., as a result of inaccuracies in or incompleteness of
                            the feed provided by the third party service provider and/or official application of the match organizer
                            comes to its attention, Offside shall use best efforts to rectify such error prior to the distribution
                            of prizes. However, Offside hereby clarifies that it relies on the accuracy and completeness of such
                            third party score/statistic feeds and does not itself warrant or make any representations concerning the
                            accuracy thereof and, in any event, shall take no responsibility for inaccuracies in computation and
                            tabulation of prediction points or the selection of winners as a result of any inaccurate or incomplete
                            scores/statistics received from such third party service provider. Users and Participants agree not to
                            make any claim or raise any complaint against Offside in this respect.
                        </p>
                    </li>
                    <li>
                        Publicity
                        <p>
                            Acceptance of a prize by the Winner constitutes permission for Offside, and its affiliates to use the
                            Winner's name, likeness, voice and comments for advertising and promotional purposes in any media
                            worldwide for purposes of advertising and trade without any further permissions or consents and / or
                            additional compensation whatsoever.
                        </p>
                        <p>
                            The Winners further undertake that they will be available for promotional purposes as planned and
                            desired by Offside without any charge. The exact dates remain the sole discretion of Offside.
                            Promotional activities may include but not be limited to press events, internal meetings and
                            ceremonies/functions.
                        </p>
                    </li>
                    <li>
                        General Conditions
                        <p>
                            If it comes to the notice of Offside that any governmental, statutory or regulatory compliances or
                            approvals are required for conducting any Contest(s) or if it comes to the notice of Offside that
                            conduct of any such Contest(s) is prohibited, then Offside shall withdraw and / or cancel such
                            Contest(s) without prior notice to any Participants or winners of any Contest(s). Users agree not to
                            make any claim in respect of such cancellation or withdrawal of the Contest or Contest it in any manner.
                        </p>
                        <p>
                            Employees, directors & affiliates of Offside, will not be eligible to participate in any Contest(s).
                        </p>
                    </li>
                    <li>
                        Dispute and Dispute Resolution
                        <ul>
                            <li>
                                The courts of competent jurisdiction at Mumbai shall have exclusive jurisdiction to determine any
                                and all disputes arising out of, or in connection with, the Offside Services provided by Offside
                                (including the Prediction contest(s)), the construction, validity, interpretation and enforceability
                                of these Terms and Conditions, or the rights and obligations of the User(s) (including Participants)
                                or Offside, as well as the exclusive jurisdiction to grant interim or preliminary relief in case of
                                any dispute referred to arbitration as given below. All such issues and questions shall be governed
                                and construed in accordance with the laws of the Republic of India.
                            </li>
                            <li>
                                In the event of any legal dispute (which may be a legal issue or question) which may arise, the
                                party raising the dispute shall provide a written notification ("Notification") to the other party.
                                On receipt of Notification, the parties shall first try to resolve the dispute through discussions.
                                In the event that the parties are unable to resolve the dispute within fifteen (15) days of receipt
                                of Notification, the dispute shall be settled by arbitration.
                            </li>
                            <li>
                                The place of arbitration shall be Mumbai, India. All arbitration proceedings shall be conducted in
                                English and in accordance with the provisions of the Arbitration and Conciliation Act, 1996, as
                                amended from time to time.
                            </li>
                            <li>
                                The arbitration award will be final and binding on the Parties, and each Party will bear its own
                                costs of arbitration and equally share the fees of the arbitrator unless the arbitral tribunal
                                decides otherwise. The arbitrator shall be entitled to pass interim orders and awards, including the
                                orders for specific performance and such orders would be enforceable in competent courts. The
                                arbitrator shall give a reasoned award.
                            </li>
                            <li>
                                Nothing contained in these Terms and Conditions shall prevent Offside from seeking and obtaining
                                interim or permanent equitable or injunctive relief, or any other relief available to safeguard
                                Offside's interest prior to, during or following the filing of arbitration proceedings or pending
                                the execution of a decision or award in connection with any arbitration proceedings from any court
                                having jurisdiction to grant the same. The pursuit of equitable or injunctive relief shall not
                                constitute a waiver on the part of Offside to pursue any remedy for monetary damages through the
                                arbitration described herein.
                            </li>
                        </ul>
                    </li>
                    <li>
                        Release and Limitations of Liability
                        <ul>
                            <li>
                                Users shall access the Offside Services provided on Offside voluntarily and at their own risk.
                                Offside shall, under no circumstances be held responsible or liable on account of any loss or damage
                                sustained (including but not limited to any accident, injury, death, loss of property) by Users or
                                any other person or entity during the course of access to the Offside Services (including
                                participation in the Prediction contest(s)) or as a result of acceptance of any prize.
                            </li>
                            <li>
                                By accessing the Offside Services provided therein, Users hereby release from and agree to indemnify
                                Offside, and/ or any of its directors, employees, partners, associates and licensors, from and
                                against all liability, cost, loss or expense arising out their access to the Offside Services
                                including (but not limited to) personal injury and damage to property and whether direct, indirect,
                                consequential, foreseeable, due to some negligent act or omission on their part, or otherwise.
                            </li>
                            <li>
                                Offside accepts no liability, whether jointly or severally, for any errors or omissions, whether on
                                behalf of itself or third parties in relation to the prizes.
                            </li>
                            <li>
                                Users shall be solely responsible for any consequences which may arise due to their access to
                                Offside Services by conducting an illegal act or due to non-conformity with these Terms and
                                Conditions and other rules and regulations in relation to Offside Services, including provision of
                                incorrect address or other personal details. Users also undertake to indemnify Offside and their
                                respective officers, directors, employees and agents on the happening of such an event (including
                                without limitation cost of attorney, legal charges etc.) on full indemnity basis for any loss/damage
                                suffered by Offside on account of such act on the part of the Users.
                            </li>
                            <li>
                                Users shall indemnify, defend, and hold Offside harmless from any third party/entity/organization
                                claims arising from or related to such User's engagement with the Offside or participation in any
                                Contest. In no event shall Offside be liable to any User for acts or omissions arising out of or
                                related to User's engagement with the Offside or his/her participation in any Contest(s).
                            </li>
                            <li>
                                In consideration of Offside allowing Users to access the Offside Services, to the maximum extent
                                permitted by law, the Users waive and release each and every right or claim, all actions, causes of
                                actions (present or future) each of them has or may have against Offside, its respective agents,
                                directors, officers, business associates, group companies, sponsors, employees, or representatives
                                for all and any injuries, accidents, or mishaps (whether known or unknown) or (whether anticipated
                                or unanticipated) arising out of the provision of Offside Services or related to the Contests or the
                                prizes of the Contests.
                            </li>
                        </ul>
                    </li>
                    <li>
                        Disclaimers
                        <ul>
                            <li>
                                To the extent permitted under law, neither Offside nor its parent/holding company, subsidiaries,
                                affiliates, directors, officers, professional advisors, employees shall be responsible for the
                                deletion, the failure to store, the mis-delivery, or the untimely delivery of any information or
                                material.
                            </li>
                            <li>
                                To the extent permitted under law, Offside shall not be responsible for any harm resulting from
                                downloading or accessing any information or material, the quality of servers, games, products,
                                Offside services or sites, cancellation of competition and prizes. Offside disclaims any
                                responsibility for, and if a User pays for access to one of Offside's Services the User will not be
                                entitled to a refund as a result of, any inaccessibility that is caused by Offside's maintenance on
                                the servers or the technology that underlies our sites, failures of Offside's service providers
                                (including telecommunications, hosting, and power providers), computer viruses, natural disasters or
                                other destruction or damage of our facilities, acts of nature, war, civil disturbance, or any other
                                cause beyond our reasonable control. In addition, Offside does not provide any warranty as to the
                                content on the Offside(s). Offside(s) content is distributed on an "as is, as available" basis.
                            </li>
                            <li>
                                Any material accessed, downloaded or otherwise obtained through Offside is done at the User's
                                discretion, competence, acceptance and risk, and the User will be solely responsible for any
                                potential damage to User's computer system or loss of data that results from a User's download of
                                any such material.
                            </li>
                            <li>
                                Offside shall make best endeavors to ensure that the Offside(s) is error-free and secure, however,
                                neither Offside nor any of its partners, licensors or associates makes any warranty that:
                            </li>
                            <ol type="a">
                                <li>
                                    the Offside(s) will meet Users' requirements,
                                </li>
                                <li>
                                    Offside(s) will be uninterrupted, timely, secure, or error free
                                </li>
                                <li>
                                    the results that may be obtained from the use of Offside(s) will be accurate or reliable; and
                                </li>
                                <li>
                                    the quality of any products, Offside Services, information, or other material that Users
                                    purchase or obtain through Offsidecom(s) will meet Users' expectations.
                                </li>
                            </ol>
                            <li>
                                In case Offside discovers any error, including any error in the determination of Winners or in the
                                transfer of amounts to a User's account, Offside reserves the right (exercisable at its discretion)
                                to rectify the error in such manner as it deems fit, including through a set-off of the erroneous
                                payment from amounts due to the User or deduction from the User's account of the amount of erroneous
                                payment. In case of exercise of remedies in accordance with this clause, Offside agrees to notify
                                the User of the error and of the exercise of the remedy(ies) to rectify the same.
                            </li>
                            <li>
                                To the extent permitted under law, neither Offside nor its partners, licensors or associates shall
                                be liable for any direct, indirect, incidental, special, or consequential damages arising out of the
                                use of or inability to use our sites, even if we have been advised of the possibility of such
                                damages.
                            </li>
                            <li>
                                Any Offside Services, events or Contest(s) being hosted or provided, or intended to be hosted on
                                Offside platform and requiring specific permission or authority from any statutory authority or any
                                state or the central government, or the board of directors shall be deemed canceled or terminated,
                                if such permission or authority is either not obtained or denied either before or after the
                                availability of the relevant Offside Services, events or Contest(s) are hosted or provided.
                            </li>
                            <li>
                                To the extent permitted under law, in the event of suspension or closure of any Services, events or
                                Contests, Users (including Participants) shall not be entitled to make any demands, claims, on any
                                nature whatsoever.
                            </li>
                        </ul>
                    </li>
                    <li>
                        Miscellaneous
                        <ul>
                            <li>
                                Offside may be required under certain legislations, to notify User(s) of certain events. User(s)
                                hereby acknowledge and consent that such notices will be effective upon Offside posting them on the
                                Offside or delivering them to the User through the email address provided by the User at the time of
                                registration. User(s) may update their email address by logging into their account on the Offside.
                                If they do not provide Offside with accurate information, Offside cannot be held liable for failure
                                to notify the User.
                            </li>
                            <li>
                                Offside shall not be liable for any delay or failure to perform resulting from causes outside its
                                reasonable control, including but not limited to any failure to perform due to unforeseen
                                circumstances or cause beyond Offside's control such as acts of God, war, terrorism, riots,
                                embargoes, acts of civil or military authorities, fire, floods, accidents, network infrastructure
                                failures, strikes, or shortages of transportation facilities, fuel, energy, labor or materials or
                                any cancellation of any cricket match to which Prediction contest relates. In such circumstances,
                                Offside shall also be entitled to cancel any related Prediction contest(s)
                            </li>
                            <li>
                                Offside's failure to exercise or enforce any right or provision of these Terms and Conditions shall
                                not constitute a waiver of such right or provision.
                            </li>
                            <li>
                                Users agree that regardless of any statute or law to the contrary, any claim or cause of action
                                arising out of or related to use of the Offside or these Terms must be filed within thirty (30) days
                                of such claim or cause of action arising or be forever barred.
                            </li>
                            <li>
                                These Terms and Conditions, including all terms, conditions, and policies that are incorporated
                                herein by reference, constitute the entire agreement between the User(s) and Kalekik Inc. and govern
                                your use of the Offside, superseding any prior agreements that any User may have with Sporta
                                Technologies Private Limited.
                            </li>
                            <li>
                                If any part of these Terms and Conditions is determined to be indefinite, invalid, or otherwise
                                unenforceable, the rest of these Terms and Conditions shall continue in full force.
                            </li>
                            <li>
                                Offside reserves the right to moderate, restrict or ban the use of the Offside, specifically to any
                                User, or generally, in accordance with Offside's policy/policies from time to time, at its sole and
                                absolute discretion and without any notice.
                            </li>
                            <li>
                                Offside may, at its sole and absolute discretion, permanently close or temporarily suspend any
                                Offside Services (including any Prediction contest(s)).
                            </li>
                        </ul>
                    </li>
                    <li>
                        Grievance Redressal Mechanism
                        <ul>
                            <li>
                                In case you have any complaints or grievance pertaining to (i) any User Content that you believe
                                violates these Terms (other than an infringement of Intellectual Property Rights) for the reporting
                                mechanism for such claims), (ii) your access to the Platform or (iii) any User Content which you
                                believe is, prima facie, in the nature of any material which is obscene, defamatory towards the
                                complainant or any person on whose behalf you are making the complaint, or is in the nature of
                                impersonation in an electronic form, including artificially morphed images of such individual,
                                please share the same with us by writing to: help@offside.club
                            </li>
                            <li>
                                In your complaint or grievance, please include the following information:
                            </li>
                            <ol type="a">
                                <li>
                                    Your name and contact details: name, address, contact number and email address;
                                </li>
                                <li>
                                    Your relation to the subject matter of the complaint, i.e. complainant or person acting on
                                    behalf of an affected person;
                                </li>
                                <li>
                                    The name and age of the person aggrieved or affected by the subject matter of the complaint, in
                                    case your are acting on behalf of such person and a statement, under penalty of perjury, that
                                    you are authorized to act on behalf of such person and to provide such person's personal
                                    information to us in relation to the complaint/grievance;
                                </li>
                                <li>
                                    Description of the complaint or grievance with clear identification of the User Content in
                                    relation to which such complaint or grievance is made;
                                </li>
                                <li>
                                    A statement that you believe, in good faith, that the User Content violates these Terms
                                </li>
                                <li>
                                    A statement that the information provided in the complaint or grievance is accurate.
                                </li>
                            </ol>
                            <li>
                                The Company respects the Intellectual Property Rights of others. All names, logos, marks, labels,
                                trademarks, copyrights or intellectual and proprietary rights on the Platform belonging to any
                                person (including User), entity or third party are recognized as proprietary to the respective
                                owners. You are requested to send us a written notice/ intimation if you notice any act of
                                infringement on the Platform, which must include the following information:
                            </li>
                            <ol type="a">
                                <li>
                                    A clear identification of the copyrighted work allegedly infringed;
                                </li>
                                <li>
                                    A clear identification of the allegedly infringing material on the Platform;
                                </li>
                                <li>
                                    Your contact details: name, address, e-mail address and phone number;
                                </li>
                                <li>
                                    A statement that you believe, in good faith, that the use of the copyrighted material allegedly
                                    infringed on the Platform is not authorized by your agent or the law;
                                </li>
                                <li>
                                    A statement that the information provided in the notice is accurate, and under penalty of
                                    perjury, that the signatory is authorized to act on behalf of the owner of an exclusive
                                    copyright right that is allegedly infringed;
                                </li>
                                <li>
                                    Your signature or a signature of your authorized agent.
                                </li>
                            </ol>
                            <li>
                                The aforesaid notices can be sent to the Company by email at grievanceofficer@Offside.com.
                            </li>
                            <li>
                                On receiving such complaint, grievance or notice, the Company reserves the right to investigate
                                and/or take such action as the Company may deem appropriate. The Company may reach out to you to
                                seek further clarification or assistance with the investigation, or verify the statements made in
                                your complaint, grievance or notice, and you acknowledge that your timely assistance with the
                                investigation would facilitate the redressal of the same.
                            </li>
                        </ul>
                    </li>
                    <li>
                        Standard Terms and Conditions of "Invite Friends" program.
                        <p>
                            The Offside Invite Friends Program lets you invite friends to join Offside ("Program"). In the event
                            that you and your referred friend meet the criteria and complete all the steps specified in these terms,
                            you can earn a successful referral, the number of successful referral will be used to give out rewards
                            to top users bi-weekly. To participate in the Program, please note our terms and conditions ("Terms") in
                            this respect, as they govern your participation in the Program:
                        </p>
                        <ul>
                            <li>
                                Eligibility – All users who: (i) have an account registered with Offside's fantasy gaming platform
                                ("Platform"); and (ii) are eligible to participate in the pay-to play game (as per the Offside's
                                terms and conditions); and (iii) have downloaded and installed the Offside Application on their
                                respective mobile devices, will be eligible to participate in the Program. Participation in the
                                Program by proxy is not permitted.
                            </li>
                            <li>
                                Participation in the Program is voluntary. A user shall not register or operate more than one user
                                account with Offside and shall not participate in the Program with more than one user account with
                                Offside.
                            </li>
                            <li>
                                By participating in the Program, you agree to and accept these Terms.
                            </li>
                            <li>
                                For the purpose of participation in the Program, you are required to have the Offside Application
                                downloaded and installed on your mobile device. Through the Offside Application, you will be
                                provided with a unique link or code, which can be shared by you ("Inviter") with friends (each an
                                "Invitee") for the purpose of inviting such friends to create and register an account with Offside
                                and download the Offside Application. On receiving the link or code from the Inviter, the Invitee
                                may either: (i) Click on the link, consequent to which such Invitee will be directed to a
                                registration page and will be provided the option to register an account with Offside and download
                                and install the Offside Application on his/her device; or (ii) download and install the Offside
                                Application on his/her device independently, register for a Offside account through the Offside
                                Application and enter the unique code shared by the Inviter where prompted in the Offside
                                Application.
                            </li>
                            <li>
                                The Inviter will be eligible to earn a successful referral subject to (amongst other terms specified
                                in these Terms): (i) the Invitee not being an existing user of Offside; and (ii) the Invitee
                                successfully registering for an account with Offside through the unique link or by using the unique
                                code shared by the Inviter; and (iii) the Inviter and Invitee agreeing to the license agreement for
                                the Offside Application and downloading and installing the Offside Application as available for the
                                Inviter’s and Invitee’s respective mobile devices. For the purposes of these Terms, an 'existing
                                user of Offside' shall mean a user who presently operates an account with the Platform or operated
                                an account with the Platform at any point of time.
                            </li>
                            <li>
                                An Invitee who is an existing user of Offside is not permitted to register a new account with the
                                Platform for the purpose of availing of a successful referral. Offside will determine in its sole
                                discretion whether an Invitee is an existing user of Offside or not and take appropriate action.
                            </li>
                            <li>
                                In the event that the Invitee opts to register for an Offside account through the Offside
                                Application, the Invitee can verify his/her contact information at the time of registration.
                            </li>
                            <li>
                                Inviter Bonus a) In order for an Inviter to be eligible to earn the successful referral due to
                                him/her, the Inviter must also download and install the Offside Application on his/her mobile
                                device. The inviter will be eligible for the running bi-weekly referral rewards depending on the
                                number of successful referrals.
                            </li>
                            <li>
                                The approval of successful referral shall be at the sole discretion of Offside and shall be subject
                                to the Inviter’s/Invitee’s compliance with these Terms. Offside may substitute or change the
                                successful referral criteria under the Program at any time without notice.
                            </li>
                            <li>
                                Offside reserves the right to:
                            </li>
                            <ol type="a">
                                <li>
                                    withhold the approval of successful referral; and/or
                                </li>
                                <li>
                                    make the inviter uneligible from the running bi-weekly referral rewards; and/or
                                </li>
                                <li>
                                    deactivate the accounts of the Inviter/Invitee, in the event that it determines or reasonably
                                    believes that such Inviter/Invitee has violated these Terms or the terms and conditions of the
                                    Offside fantasy games.
                                </li>
                            </ol>
                            <li>
                                Offside may, at its sole and absolute discretion, disqualify any Inviter/Invitee if such
                                Inviter/Invitee engages in or it is found that such Inviter/Invitee has engaged in any illegal,
                                unlawful or improper conduct (with regard to the Program or otherwise).
                            </li>
                            <li>
                                The decision of Offside will be final and binding with regard to the Program, and the deposit of the
                                Bonus Amount and the Invitee Discount and no correspondence, objection, complaints, etc. will be
                                entertained in this regard.
                            </li>
                            <li>
                                Offside reserves the right to change/modify/or withdraw the Program and/or change these terms and
                                conditions without any prior notice of the same at its sole discretion.
                            </li>
                            <li>
                                The Terms and Conditions, as applicable to the Offside's fantasy games and services, will apply to
                                and govern the Program.
                            </li>
                            <li>
                                Offside does not make any commitment, express or implied, to respond to any feedback, suggestion
                                and, or, queries of the participants (Inviter/Invitee) of the Program.
                            </li>
                        </ul>

                    </li>
                </ol>
            </div>

        </div>
    )
}

export default Terms;